<?php

if (!defined('BASEPATH'))
  exit('No direct script access allowed');

class Login_voucher extends CI_Controller
{
  public function __construct()
  {
    parent::__construct();
    $this->load->database();
    $this->load->library(array('ion_auth', 'form_validation'));
    $this->load->helper(array('url', 'language'));
    $this->load->model('Voucher_model');

    // $this->form_validation->set_error_delimiters($this->config->item('error_start_delimiter', 'ion_auth'), $this->config->item('error_end_delimiter', 'ion_auth'));


  }


  public function index()
  {
    if ($this->session->nama) {
      redirect('login_voucher/dashboard');
    } else {

      $this->load->view('auth/voucher');
    }
  }
  public function dashboard()
  {
    $this->load->view('auth/v_dashboard');
  }
  public function login()
  {
    $username = $this->input->post('username');
    $password = $this->input->post('password');
    // var_dump($password);
    // exit;
    $where = array(
      'username' => $username,
      'password' => $password
    );


    $cek = $this->Voucher_model->cek_login($where)->num_rows();
    if ($cek > 0) {
      // cek apakah ada
      $masa_aktif = $this->db->query("select masa_aktif,status from voucher where username = '$username'")->row();
      $masa_aktif = $masa_aktif->masa_aktif;
      $hari_ini = date('Y-m-d H:i:s');
      $status = $masa_aktif->status;
      // var_dump($status);
      if (strtotime($masa_aktif) > strtotime($hari_ini)) {
        // cek masa atif

        $data_session = array(
          'nama' => $username,
          'masa_aktif' => $masa_aktif,
          'status' => "login"
        );

        $this->session->set_userdata($data_session);
        redirect(base_url('login_voucher/dashboard'));
      } else {
        $this->db->query("UPDATE VOUCHER SET status='0' where username='$username'");
        redirect(base_url('login_voucher/'));
      }
    } else {
      echo "Username dan password salah !";
    }
    $this->load->view('auth/voucher');
  }

  function logout()
  {
    $this->session->sess_destroy();
    redirect(base_url('login_voucher'));
  }
}

/* End of file Voucher.php */
/* Location: ./application/controllers/Voucher.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-06 08:06:27 */
/* http://harviacode.com */